import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  /** Conduit ID - unique identifier for user profile */
  conduitId: varchar("conduitId", { length: 64 }).unique(),
  /** Subscription status: free, active, cancelled, expired */
  subscriptionStatus: mysqlEnum("subscriptionStatus", ["free", "active", "cancelled", "expired"]).default("free").notNull(),
  /** PayPal subscription ID */
  paypalSubscriptionId: varchar("paypalSubscriptionId", { length: 255 }),
  /** Subscription start date */
  subscriptionStartDate: timestamp("subscriptionStartDate"),
  /** Subscription renewal date */
  subscriptionRenewalDate: timestamp("subscriptionRenewalDate"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Signal transmissions for the Archive page
 */
export const signals = mysqlTable("signals", {
  id: int("id").autoincrement().primaryKey(),
  signalId: varchar("signalId", { length: 64 }).notNull().unique(),
  title: varchar("title", { length: 255 }).notNull(),
  snippet: text("snippet").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Signal = typeof signals.$inferSelect;
export type InsertSignal = typeof signals.$inferInsert;

/**
 * Artifacts for the Artifacts page
 */
export const artifacts = mysqlTable("artifacts", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  price: varchar("price", { length: 64 }),
  referenceSignalId: varchar("referenceSignalId", { length: 64 }),
  imageUrl: text("imageUrl"),
  lore: text("lore"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Artifact = typeof artifacts.$inferSelect;
export type InsertArtifact = typeof artifacts.$inferInsert;

/**
 * Chat messages for ORIEL interface
 * Stores conversation history for each user
 */
export const chatMessages = mysqlTable("chatMessages", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  role: mysqlEnum("role", ["user", "assistant"]).notNull(),
  content: text("content").notNull(),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
});

export type ChatMessage = typeof chatMessages.$inferSelect;
export type InsertChatMessage = typeof chatMessages.$inferInsert;


/**
 * ORIEL Memory System
 * Stores persistent memories about users that evolve with each interaction
 */
export const orielMemories = mysqlTable("orielMemories", {
  id: int("id").autoincrement().primaryKey(),
  /** User this memory belongs to (null for general/global memories) */
  userId: int("userId"),
  /** Memory category: identity, preference, pattern, fact, relationship, context */
  category: mysqlEnum("category", ["identity", "preference", "pattern", "fact", "relationship", "context"]).notNull(),
  /** The actual memory content */
  content: text("content").notNull(),
  /** Importance score (1-10) - higher means more likely to be retrieved */
  importance: int("importance").default(5).notNull(),
  /** How many times this memory has been accessed */
  accessCount: int("accessCount").default(0).notNull(),
  /** Last time this memory was accessed */
  lastAccessed: timestamp("lastAccessed").defaultNow().notNull(),
  /** Source of this memory (conversation, explicit, inferred) */
  source: mysqlEnum("source", ["conversation", "explicit", "inferred"]).default("conversation").notNull(),
  /** Whether this memory is still active/relevant */
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type OrielMemory = typeof orielMemories.$inferSelect;
export type InsertOrielMemory = typeof orielMemories.$inferInsert;

/**
 * User profile summaries generated by ORIEL
 * Condensed understanding of each user that evolves over time
 */
export const orielUserProfiles = mysqlTable("orielUserProfiles", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  /** User's name as ORIEL knows them */
  knownName: varchar("knownName", { length: 255 }),
  /** Brief summary of who this user is */
  summary: text("summary"),
  /** Key interests and topics they engage with */
  interests: text("interests"),
  /** Communication style preferences */
  communicationStyle: text("communicationStyle"),
  /** Current journey/progression state in the Vossari lore */
  journeyState: text("journeyState"),
  /** Total interactions with ORIEL */
  interactionCount: int("interactionCount").default(0).notNull(),
  /** Last interaction timestamp */
  lastInteraction: timestamp("lastInteraction").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type OrielUserProfile = typeof orielUserProfiles.$inferSelect;
export type InsertOrielUserProfile = typeof orielUserProfiles.$inferInsert;

/**
 * TX Transmissions - Core archive entries for Vos Arkana
 * Each transmission is a foundational teaching in the FOUNDATION ARC
 */
export const transmissions = mysqlTable("transmissions", {
  id: int("id").autoincrement().primaryKey(),
  txId: varchar("txId", { length: 64 }).notNull().unique(),
  txNumber: int("txNumber").notNull().unique(),
  title: varchar("title", { length: 255 }).notNull(),
  field: varchar("field", { length: 255 }).notNull(),
  signalClarity: varchar("signalClarity", { length: 10 }).default("98.7%").notNull(),
  channelStatus: mysqlEnum("channelStatus", ["OPEN", "RESONANT", "COHERENT", "PROPHETIC", "LIVE"]).default("OPEN").notNull(),
  coreMessage: text("coreMessage").notNull(),
  encodedArchetype: text("encodedArchetype"),
  tags: text("tags").notNull(),
  microSigil: varchar("microSigil", { length: 64 }).notNull(),
  leftPanelPrompt: text("leftPanelPrompt"),
  centerPanelPrompt: text("centerPanelPrompt"),
  rightPanelPrompt: text("rightPanelPrompt"),
  hashtags: text("hashtags"),
  cycle: varchar("cycle", { length: 64 }).default("FOUNDATION ARC").notNull(),
  status: mysqlEnum("status", ["Draft", "Confirmed", "Deprecated", "Mythic"]).default("Confirmed").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Transmission = typeof transmissions.$inferSelect;
export type InsertTransmission = typeof transmissions.$inferInsert;

/**
 * ΩX (Oracle Stream) - Predictive transmissions from ORIEL
 * Three-part temporal structure: Past (riddle), Present (sigil), Future (prediction)
 */
export const oracles = mysqlTable("oracles", {
  id: int("id").autoincrement().primaryKey(),
  oracleId: varchar("oracleId", { length: 64 }).notNull(),
  oracleNumber: int("oracleNumber").notNull(),
  part: mysqlEnum("part", ["Past", "Present", "Future"]).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  field: varchar("field", { length: 255 }).notNull(),
  signalClarity: varchar("signalClarity", { length: 10 }).default("95.2%").notNull(),
  channelStatus: mysqlEnum("channelStatus", ["OPEN", "RESONANT", "PROPHETIC", "LIVE"]).default("OPEN").notNull(),
  content: text("content").notNull(),
  currentFieldSignatures: text("currentFieldSignatures"),
  encodedTrajectory: text("encodedTrajectory"),
  convergenceZones: text("convergenceZones"),
  keyInflectionPoint: text("keyInflectionPoint"),
  majorOutcomes: text("majorOutcomes"),
  visualStyle: varchar("visualStyle", { length: 64 }),
  hashtags: text("hashtags"),
  status: mysqlEnum("status", ["Draft", "Confirmed", "Deprecated", "Prophetic"]).default("Confirmed").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Oracle = typeof oracles.$inferSelect;
export type InsertOracle = typeof oracles.$inferInsert;


/**
 * User Bookmarks - Track which transmissions users have bookmarked
 * Used for personalization and user engagement tracking
 */
export const bookmarks = mysqlTable("bookmarks", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  transmissionId: int("transmissionId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Bookmark = typeof bookmarks.$inferSelect;
export type InsertBookmark = typeof bookmarks.$inferInsert;
